# Generated by Django 4.1.3 on 2022-11-26 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Taller', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientes',
            old_name='telefono',
            new_name='numero',
        ),
        migrations.RenameField(
            model_name='proveedores',
            old_name='telefono',
            new_name='numero',
        ),
    ]
